FROM registry.access.redhat.com/ubi9/python-39:1@sha256:81a000d48bca6b09e09a7b834e0b7c8b6ffb1907b7867e76df9b044e02f9a2ac

LABEL version="1.3.0"
LABEL repository="http://github.com/redhat-cop/github-actions"
LABEL homepage="http://github.com/redhat-cop/github-actions/redhat-csp-download"
LABEL maintainer="Red Hat CoP"
LABEL "com.github.actions.name"="redhat-csp-download"
LABEL "com.github.actions.description"="Run redhat-csp-download to download resources from the Red Hat Customer Portal."
LABEL "com.github.actions.branding.icon"="monitor"
LABEL "com.github.actions.branding.color"="purple"

COPY ansible /ansible
RUN pip3 install --no-cache-dir -r /ansible/requirements.txt && \
    ansible --version && \
    ansible-galaxy --version && \
    ansible-playbook --version

USER root

RUN dnf upgrade --assumeyes && \
    dnf clean all

USER 1001

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
