FROM registry.access.redhat.com/ubi9/python-39:1-172@sha256:195c51368e83a798b6f79c6a5d877685fdf5297a81e5211cfca747a7fca725aa

LABEL version="4.0.0"
LABEL repository="http://github.com/redhat-cop/github-actions"
LABEL homepage="http://github.com/redhat-cop/github-actions/redhat-csp-download"
LABEL maintainer="Red Hat CoP"
LABEL "com.github.actions.name"="redhat-csp-download"
LABEL "com.github.actions.description"="Run redhat-csp-download to download resources from the Red Hat Customer Portal."
LABEL "com.github.actions.branding.icon"="monitor"
LABEL "com.github.actions.branding.color"="purple"

COPY ansible /ansible
RUN pip3 install --no-cache-dir -r /ansible/requirements.txt && \
    ansible --version && \
    ansible-galaxy --version && \
    ansible-playbook --version

USER root

RUN dnf upgrade --assumeyes && \
    dnf clean all

USER 1001

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
