# renovate: datasource=github-releases depName=redhat-cop/github-actions
FROM ghcr.io/redhat-cop/github-actions/redhat-csp-download:v4.3@sha256:936c5330bb1a37ecf52c42fee06d31d8c573b929f55cf82d4ead47b3e6e26ad9
