# renovate: datasource=github-releases depName=redhat-cop/github-actions
FROM ghcr.io/redhat-cop/github-actions/redhat-csp-download:v4.4.0@sha256:df6e126ade2f52ebe45efe13f2cd7c825bd6a2203086c1fee4cc7b7d87ab11b0
