# renovate: datasource=github-releases depName=redhat-cop/github-actions
FROM ghcr.io/redhat-cop/github-actions/redhat-csp-download:v4.0@sha256:c2729b245aec118228318580396900b1aa616210bec22450d8786dbce0a65f2e
