# renovate: datasource=github-releases depName=redhat-cop/github-actions
FROM ghcr.io/redhat-cop/github-actions/confbatstest:v4.0@sha256:4875ee7e4779b5627d06b31d3b023d84bb5952b2c5c8fb51857edd76645cac49
