# Builder image for go
FROM registry.access.redhat.com/ubi9/go-toolset:1.20.10-2.1699551725@sha256:310fbbc9b2a6af87d730e244d5b20a1836df3ae295c290ffec2d4ef6a53a33f8 AS go-builder

# go1.19 not released yet - so need to manaully upgrade
USER root
RUN curl -L -o /tmp/go1.19.linux-amd64.tar.gz https://go.dev/dl/go1.19.linux-amd64.tar.gz && \
    tar -xzf /tmp/go1.19.linux-amd64.tar.gz && \
    mv go /usr/local && \
    PATH="/usr/local/go/bin:$PATH" && \
    go version

RUN PATH="/usr/local/go/bin:$PATH" GOBIN=/tmp/go-bin go install github.com/plexsystems/konstraint@latest && \
    /tmp/go-bin/konstraint --help

# Builder image
FROM registry.access.redhat.com/ubi9/ubi:9.1@sha256:49124e4acd09c98927882760476d617a85f155cb45759aea56b2ab020563c4b8 AS builder

RUN export HELM_VERSION=3.11.1 && \
    curl -L -o /tmp/helm-v${HELM_VERSION}-linux-amd64.tar.gz https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz && \
    tar -C /tmp -xzf /tmp/helm-v${HELM_VERSION}-linux-amd64.tar.gz && \
    /tmp/linux-amd64/helm version

RUN export JQ_VERSION=1.6 && \
    curl -L -o /tmp/jq-linux64 https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64 && \
    chmod +x /tmp/jq-linux64 && \
    /tmp/jq-linux64 --version

RUN export OC_VERSION=4.12.0 && \
    curl -L -o /tmp/openshift-client-linux.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OC_VERSION}/openshift-client-linux.tar.gz && \
    tar -C /tmp -xzf /tmp/openshift-client-linux.tar.gz && \
    /tmp/oc version --client && \
    /tmp/kubectl version --client

RUN export OPA_VERSION=v0.49.2 && \
    curl -L -o /tmp/opa_linux_amd64 https://github.com/open-policy-agent/opa/releases/download/${OPA_VERSION}/opa_linux_amd64 && \
    chmod +x /tmp/opa_linux_amd64 && \
    /tmp/opa_linux_amd64 --help

RUN export CONFTEST_VERSION=0.39.2 && \
    curl -L -o /tmp/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz && \
    tar -C /tmp -xzf /tmp/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz && \
    /tmp/conftest --version

RUN export KUBEVAL_VERSION=latest && \
    curl -L -o /tmp/kubeval-linux-amd64.tar.gz https://github.com/instrumenta/kubeval/releases/${KUBEVAL_VERSION}/download/kubeval-linux-amd64.tar.gz && \
    tar -C /tmp -xzf /tmp/kubeval-linux-amd64.tar.gz && \
    /tmp/kubeval --version

# Runnable image
FROM registry.access.redhat.com/ubi9/python-39:1-153.1699551718@sha256:81a000d48bca6b09e09a7b834e0b7c8b6ffb1907b7867e76df9b044e02f9a2ac

LABEL version="1.8.0"
LABEL repository="http://github.com/redhat-cop/github-actions"
LABEL homepage="http://github.com/redhat-cop/github-actions/confbatstest"
LABEL maintainer="Red Hat CoP"
LABEL "com.github.actions.name"="confbatstest"
LABEL "com.github.actions.description"="Run conftest using BATS"
LABEL "com.github.actions.branding.icon"="monitor"
LABEL "com.github.actions.branding.color"="purple"

COPY --from=builder /tmp/linux-amd64/helm /usr/local/bin/helm
RUN helm version

COPY --from=builder /tmp/jq-linux64 /usr/local/bin/jq
RUN jq --version

COPY --from=builder /tmp/oc /usr/local/bin/oc
COPY --from=builder /tmp/kubectl /usr/local/bin/kubectl
RUN oc version --client && \
    kubectl version --client

COPY --from=builder /tmp/opa_linux_amd64 /usr/local/bin/opa
RUN opa --help

COPY --from=builder /tmp/conftest /usr/local/bin/conftest
RUN conftest --version

COPY --from=builder /tmp/kubeval /usr/local/bin/kubeval
RUN kubeval --version

COPY --from=go-builder /tmp/go-bin/konstraint /usr/local/bin/konstraint
RUN konstraint --help

USER root

RUN dnf upgrade --assumeyes && \
    dnf install --assumeyes --nodocs findutils diffutils bc && \
    dnf clean all && \
    git --version && \
    diff --version && \
    bc --version

RUN export BATS_VERSION=master && \
    curl -L -o /tmp/${BATS_VERSION}.tar.gz https://github.com/bats-core/bats-core/archive/${BATS_VERSION}.tar.gz && \
    tar -C /tmp -xzf /tmp/${BATS_VERSION}.tar.gz && \
    /tmp/bats-core-${BATS_VERSION}/install.sh /tmp/bats && \
    ln -s /tmp/bats/bin/bats /usr/local/bin/bats && \
    bats --version

USER 1001

COPY requirements.txt /requirements.txt
RUN pip3 install --no-cache-dir -r /requirements.txt && \
    yq --version

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
