# renovate: datasource=github-releases depName=redhat-cop/github-actions
FROM ghcr.io/redhat-cop/github-actions/kyverno-cli:v4.0@sha256:7e8af31b4aecfd578616c8ec4268a4637cf89a85332a6e1c7a1d21f2a066a0a6
