# renovate: datasource=github-releases depName=redhat-cop/github-actions
FROM ghcr.io/redhat-cop/github-actions/kyverno-cli:v4.4.0@sha256:0fc78e89d82a8f35a6fae7c07a3e46f8e7dee25e0c130d96360fd4439478180e
