# Builder image
FROM registry.access.redhat.com/ubi9/ubi:9.4-1123.1719560047@sha256:081c96d1b1c7cd1855722d01f1ca53360510443737b1eb33284c6c4c330e537c AS builder

# renovate: datasource=github-releases depName=helm/helm
ARG HELM_VERSION=v3.15.3
# renovate: datasource=github-releases depName=stedolan/jq
ARG JQ_VERSION=1.6
# renovate: datasource=repology depName=homebrew/openshift-cli
ARG OC_VERSION=4.16.0
# renovate: datasource=github-releases depName=open-policy-agent/opa
ARG KYVERNO_VERSION=v1.9.0

RUN curl -L -o /tmp/helm-${HELM_VERSION}-linux-amd64.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz && \
    tar -C /tmp -xzf /tmp/helm-${HELM_VERSION}-linux-amd64.tar.gz && \
    /tmp/linux-amd64/helm version

RUN curl -L -o /tmp/jq-linux64 https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64 && \
    chmod +x /tmp/jq-linux64 && \
    /tmp/jq-linux64 --version

RUN curl -L -o /tmp/openshift-client-linux.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OC_VERSION}/openshift-client-linux.tar.gz && \
    tar -C /tmp -xzf /tmp/openshift-client-linux.tar.gz && \
    /tmp/oc version --client && \
    /tmp/kubectl version --client

RUN curl -L -o /tmp/kyverno-cli_${KYVERNO_VERSION}_linux_x86_64.tar.gz https://github.com/kyverno/kyverno/releases/download/${KYVERNO_VERSION}/kyverno-cli_${KYVERNO_VERSION}_linux_x86_64.tar.gz && \
    tar -C /tmp -xzf /tmp/kyverno-cli_${KYVERNO_VERSION}_linux_x86_64.tar.gz && \
    /tmp/kyverno --help

# Runnable image
FROM registry.access.redhat.com/ubi9/python-39:1-186.1720018722@sha256:145f08b49fabbfec82c9042f6de0d3160c6005ecf700b7fcee3c482e24fd0bf6

# renovate: datasource=github-releases depName=bats-core/bats-core
ARG BATS_VERSION=master

LABEL version="4.0.0"
LABEL repository="http://github.com/redhat-cop/github-actions"
LABEL homepage="http://github.com/redhat-cop/github-actions/kyverno-cli"
LABEL maintainer="Red Hat CoP"
LABEL "com.github.actions.name"="kyverno-cli"
LABEL "com.github.actions.description"="Run kyverno using BATS"
LABEL "com.github.actions.branding.icon"="monitor"
LABEL "com.github.actions.branding.color"="purple"

COPY --from=builder /tmp/linux-amd64/helm /usr/local/bin/helm
RUN helm version

COPY --from=builder /tmp/jq-linux64 /usr/local/bin/jq
RUN jq --version

COPY --from=builder /tmp/oc /usr/local/bin/oc
COPY --from=builder /tmp/kubectl /usr/local/bin/kubectl
RUN oc version --client && \
    kubectl version --client

COPY --from=builder /tmp/kyverno /usr/local/bin/kyverno
RUN kyverno --help

USER root

RUN dnf upgrade --assumeyes && \
    dnf install --assumeyes --nodocs findutils diffutils bc && \
    dnf clean all && \
    git --version && \
    diff --version && \
    bc --version

RUN curl -L -o /tmp/${BATS_VERSION}.tar.gz https://github.com/bats-core/bats-core/archive/${BATS_VERSION}.tar.gz && \
    tar -C /tmp -xzf /tmp/${BATS_VERSION}.tar.gz && \
    /tmp/bats-core-${BATS_VERSION}/install.sh /tmp/bats && \
    ln -s /tmp/bats/bin/bats /usr/local/bin/bats && \
    bats --version

USER 1001

COPY requirements.txt /requirements.txt
RUN pip3 install --no-cache-dir -r /requirements.txt && \
    yq --version

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
