# renovate: datasource=github-releases depName=redhat-cop/github-actions
FROM ghcr.io/redhat-cop/github-actions/kyverno-cli:v4.0@sha256:343c64052374dbc66bd3af0e0fc376d671a212060f4ad0386bf91cc798be7b81
