# Builder image
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.1 AS builder

RUN export JQ_VERSION=1.6 && \
    curl -L -o /tmp/jq-linux64 https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64 && \
    chmod +x /tmp/jq-linux64 && \
    /tmp/jq-linux64 --version

# Runnable image
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.1

LABEL version="1.2.0"
LABEL repository="http://github.com/redhat-cop/github-actions"
LABEL homepage="http://github.com/redhat-cop/github-actions/github-dispatches"
LABEL maintainer="Red Hat CoP"
LABEL "com.github.actions.name"="github-dispatches"
LABEL "com.github.actions.description"="Triggers a GitHub CI dispatches event."
LABEL "com.github.actions.branding.icon"="monitor"
LABEL "com.github.actions.branding.color"="purple"

COPY --from=builder /tmp/jq-linux64 /usr/local/bin/jq
RUN jq --version

RUN microdnf upgrade --assumeyes && \
    microdnf clean all

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
