# renovate: datasource=github-releases depName=redhat-cop/github-actions
FROM ghcr.io/redhat-cop/github-actions/github-dispatches:v4.3@sha256:ab25a23e25232d5b4cccfdcc853440e24f6a26196edde3c5c99366885c87bba2
