# renovate: datasource=github-releases depName=redhat-cop/github-actions
FROM ghcr.io/redhat-cop/github-actions/github-dispatches:v4.0@sha256:0e50e08bceb17924751ef9052447c6ce8f49f4af4e50d8bb6628b9dde541b587
