# renovate: datasource=github-releases depName=redhat-cop/github-actions
FROM ghcr.io/redhat-cop/github-actions/github-dispatches:v4.2@sha256:fdb786dad72101780f1ce4010efbe5096b5cf6390c4faa2b7bff8fd2b9ace3a9
