name: Test confbatstest

on:
  push:
    paths:
      - .github/workflows/confbatstest.yaml
      - confbatstest/**
  pull_request:
    paths:
      - .github/workflows/confbatstest.yaml
      - confbatstest/**
  schedule:
    - cron: "0 0 1 * *"

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Switch the action to use the Dockerfile_build
        run: |
          mv confbatstest/Dockerfile confbatstest/Dockerfile_runnable
          mv confbatstest/Dockerfile_build confbatstest/Dockerfile

      - name: confbatstest - tests
        uses: ./confbatstest
        with:
          tests: confbatstest/_test/conftest.sh

      - name: confbatstest - raw
        uses: ./confbatstest
        with:
          raw: konstraint doc -o POLICIES.md

      - name: Check POLICIES.md file exists
        run: |
          FILE="POLICIES.md"
          if [ -f "$FILE" ]; then
            echo "$FILE exists."
          else
            echo "$FILE does not exist."
            exit 1
          fi