name: Test confbatstest

on:
  push:
    paths:
      - .github/workflows/confbatstest.yaml
      - confbatstest/**
  pull_request:
    paths:
      - .github/workflows/confbatstest.yaml
      - confbatstest/**

# Declare default permissions as read only.
permissions: read-all

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: confbatstest/Dockerfile_build
          ignore: DL3041 # https://github.com/hadolint/hadolint/wiki/DL3041

      - name: Switch the action to use the Dockerfile_build
        run: |
          mv confbatstest/Dockerfile confbatstest/Dockerfile_runnable
          mv confbatstest/Dockerfile_build confbatstest/Dockerfile

      - name: confbatstest - tests
        uses: ./confbatstest
        with:
          tests: confbatstest/_test/conftest.sh

      - name: confbatstest - raw
        uses: ./confbatstest
        with:
          raw: konstraint doc -o POLICIES.md

      - name: Check POLICIES.md file exists
        run: |
          FILE="POLICIES.md"
          if [ -f "$FILE" ]; then
            echo "$FILE exists."
          else
            echo "$FILE does not exist."
            exit 1
          fi