name: Test get-image-version

on:
  push:
    paths:
      - .github/workflows/get-image-version.yaml
      - get-image-version/**
  pull_request:
    paths:
      - .github/workflows/get-image-version.yaml
      - get-image-version/**

# Declare default permissions as read only.
permissions: read-all

jobs:
  get-image-version:
    env:
      CONTEXT_DIR: get-image-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: get-image-version - tests
        id: get_image_version
        uses: ./get-image-version
        with:
          IMAGE_CONTEXT_DIR: ${{ env.CONTEXT_DIR }}/_test

      - name: Check outputs are correct
        run: |
          tags="${{ steps.get_image_version.outputs.IMAGE_TAGS }}"

          echo "VERSION == ${{ steps.get_image_version.outputs.VERSION }}"
          echo "MINOR_VERSION == ${{ steps.get_image_version.outputs.MINOR_VERSION }}"
          echo "IMAGE_TAGS == ${tags[*]}"

          if [[ "${{ steps.get_image_version.outputs.VERSION }}" != "v1.32.1" ]]; then
              echo "VERSION missmatch"
              exit 1
          fi

          if [[ "${{ steps.get_image_version.outputs.MINOR_VERSION }}" != "v1.32" ]]; then
              echo "MINOR_VERSION missmatch"
              exit 1
          fi
          
          expected_tags=("latest" "v1.32.1" "v1.32")
          if [[ "${GITHUB_REF}" =~ refs/tags/(.*) ]]; then
            expected_tags+=("git-${BASH_REMATCH[1]}")
          fi

          if [[ "${tags[*]}" != "${expected_tags[*]}" ]]; then
              echo "IMAGE_TAGS missmatch"
              exit 1
          fi