name: Build kyverno-cli

on:
  push:
    paths:
      - .github/workflows/kyverno-cli-build.yaml
      - kyverno-cli/**

# Declare default permissions as read only.
permissions: read-all

jobs:
  build-kyverno-cli:
    env:
      context: kyverno-cli
      image_name: kyverno-cli
      branch_name: ${{ github.head_ref || github.ref_name }}
      ref_type: ${{ github.ref_type }}
      owner: ${{ github.repository_owner }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Get image tags
        id: image_tags
        uses: redhat-cop/github-actions/get-image-version@main
        with:
          IMAGE_CONTEXT_DIR: ${{ env.context }}

      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: kyverno-cli/Dockerfile_build
          ignore: DL3041 # https://github.com/hadolint/hadolint/wiki/DL3041

      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2
        with:
          context: ${{ env.context }}
          dockerfiles: |
            ./${{ env.context }}/Dockerfile_build
          image: ${{ env.image_name }}
          oci: true
          tags: "${{ steps.image_tags.outputs.IMAGE_TAGS }}"

      - name: Push to ghcr.io
        if: ${{ env.ref_type == 'tag' || env.owner != 'redhat-cop' }} # Stops push running when bots create a PR, which fails due to token
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          registry: ghcr.io/${{ github.repository }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.build_image.outputs.tags }}