name: Build ssh-agent

on:
  push:
    paths:
      - .github/workflows/ssh-agent-build.yaml
      - ssh-agent/**
  pull_request:
    paths:
      - .github/workflows/ssh-agent-build.yaml
      - ssh-agent/**

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24

      - name: Install Node.js dependencies
        run: |
          pushd ssh-agent/
          npm ci
          popd

      - name: Run linters
        run: |
          pushd ssh-agent/
          npm run prettier
          npm run eslint
          popd

      - name: Compile Node.js dependencies
        run: |
          pushd ssh-agent/
          npm run compile
          popd
